# Generated by Django 5.0.3 on 2024-06-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='no description', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catagory',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
