# Generated by Django 5.0.3 on 2024-06-10 04:39

import django.db.models.deletion
import parlour.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0002_product_short_description_alter_catagory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=parlour.models.getfilename)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='parlour.product')),
            ],
        ),
    ]
