# Generated by Django 5.0.3 on 2024-06-10 06:28

import parlour.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0003_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=parlour.models.getfilename),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=parlour.models.getfilename),
        ),
    ]
