# Generated by Django 5.0.3 on 2024-06-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0005_callbackrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callbackrequest',
            name='preferred_time',
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
