# Generated by Django 5.0.3 on 2024-06-10 15:32

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0006_remove_callbackrequest_preferred_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackrequest',
            name='Message',
            field=models.CharField(default=datetime.datetime(2024, 6, 10, 15, 31, 22, 831820, tzinfo=datetime.timezone.utc), max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callbackrequest',
            name='service',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
