# Generated by Django 5.0.3 on 2024-06-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0007_callbackrequest_message_callbackrequest_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequest',
            name='name',
            field=models.CharField(help_text='Name', max_length=50),
        ),
    ]
