# Generated by Django 5.0.3 on 2024-06-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0008_alter_callbackrequest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequest',
            name='Message',
            field=models.CharField(help_text='Intrested in', max_length=150),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='email',
            field=models.EmailField(help_text='Email Address', max_length=50),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='phone_number',
            field=models.CharField(help_text='Mobile No', max_length=10),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='service',
            field=models.CharField(help_text='Message', max_length=50),
        ),
    ]
