# Generated by Django 5.0.3 on 2024-06-11 12:03

import parlour.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0009_alter_callbackrequest_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAndRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=150)),
                ('rating', models.FloatField()),
                ('status', models.BooleanField(default=True, help_text='0-Avaliable 1-Suspended')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=parlour.models.getfilename)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='Message',
            field=models.CharField(help_text='Customer Message', max_length=150),
        ),
        migrations.AlterField(
            model_name='callbackrequest',
            name='service',
            field=models.CharField(help_text='Customer intrested service', max_length=50),
        ),
    ]
