# Generated by Django 5.0.3 on 2024-06-11 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0010_reviewandrating_alter_callbackrequest_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewandrating',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='reviewandrating',
            name='status',
            field=models.BooleanField(default=True, help_text='0-Available 1-Suspended'),
        ),
    ]
