# Generated by Django 5.0.3 on 2024-06-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0011_alter_reviewandrating_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewandrating',
            name='text',
            field=models.CharField(max_length=250),
        ),
    ]
