# Generated by Django 5.0.3 on 2024-06-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0012_alter_reviewandrating_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewandrating',
            name='status',
            field=models.BooleanField(default=False, help_text='0-Available 1-Suspended'),
        ),
    ]
