# Generated by Django 5.0.3 on 2024-06-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0013_alter_reviewandrating_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewandrating',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
