# Generated by Django 5.0.3 on 2024-06-18 01:45

import parlour.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0014_reviewandrating_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogcat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to=parlour.models.getfilename)),
            ],
        ),
    ]
