# Generated by Django 5.0.3 on 2024-06-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0015_blogcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcat',
            name='status',
            field=models.BooleanField(default=False, help_text='0-Available 1-Suspended'),
        ),
    ]
