# Generated by Django 5.0.3 on 2024-06-18 11:09

import django.utils.timezone
import parlour.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0016_blogcat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcat',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogcat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=parlour.models.getfilenames),
        ),
    ]
