# Generated by Django 5.0.3 on 2024-06-19 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0017_blogcat_author_alter_blogcat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcat',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
