# Generated by Django 5.0.3 on 2024-06-20 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0019_blogcat_description1_blogcat_description2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcat',
            name='About_Author',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
